import { Country } from "@/types/country";

export const countries: Country[] = [
  {
    slug: "russia",
    name: "Russia",
    flagEmoji: "🇷🇺",
    heroImage: "/images/countries/russia-hero.jpg",
    tagline: "World-class medical education at globally recognized universities",
    overview:
      "Russia is one of the most popular destinations for Indian students pursuing MBBS abroad, home to universities recognized by WHO, NMC, and other global bodies. With affordable tuition, English-medium programs, and a strong legacy of medical education, Russia offers a reliable pathway to becoming a licensed doctor.",
    quickFacts: {
      duration: "6 years (including internship)",
      medium: "English",
      intake: "September",
      recognition: "WHO, NMC, ECFMG",
      avgTuitionPerYear: "₹3.5 - 5.5 Lakhs",
      avgLivingCostPerYear: "₹1.5 - 2.5 Lakhs",
    },
    universities: [
      {
        name: "Kazan State Medical University",
        city: "Kazan",
        established: 1814,
        ranking: "Top 5 in Russia",
        recognition: ["NMC", "WHO", "ECFMG"],
      },
      {
        name: "Crimea Federal University",
        city: "Simferopol",
        established: 1918,
        recognition: ["NMC", "WHO"],
      },
      {
        name: "Volgograd State Medical University",
        city: "Volgograd",
        established: 1935,
        recognition: ["NMC", "WHO", "ECFMG"],
      },
    ],
    tuitionFees: [
      { label: "1st Year Tuition", amount: "₹3.5 - 4 Lakhs" },
      { label: "Hostel Fee (per year)", amount: "₹50,000 - 80,000" },
      { label: "One-time Admission Fee", amount: "₹40,000 - 60,000" },
    ],
    livingCosts: [
      { label: "Food", amount: "₹6,000 - 8,000/month" },
      { label: "Local Transport", amount: "₹1,500 - 2,000/month" },
      { label: "Miscellaneous", amount: "₹3,000/month" },
    ],
    eligibility: [
      "Minimum 50% in PCB (Physics, Chemistry, Biology) in 10+2 (45% for reserved categories)",
      "Valid NEET qualifying score",
      "Minimum age of 17 years at the time of admission",
    ],
    admissionProcess: [
      { step: 1, title: "Document Verification", description: "Submit academic records and NEET scorecard for eligibility check." },
      { step: 2, title: "University Selection", description: "Choose a university based on budget, ranking, and city preference." },
      { step: 3, title: "Invitation Letter", description: "Receive an official invitation letter from the university." },
      { step: 4, title: "Visa Processing", description: "Apply for a Russian student visa with the invitation letter." },
      { step: 5, title: "Departure & Enrollment", description: "Travel to Russia and complete on-campus enrollment." },
    ],
    documentsRequired: [
      "10th and 12th mark sheets",
      "NEET admit card and scorecard",
      "Passport (valid for 2+ years)",
      "Passport-size photographs",
      "Birth certificate",
      "Medical fitness certificate",
    ],
    advantages: [
      "Low tuition fees compared to private colleges in India",
      "No donation or capitation fees",
      "Globally recognized degree valid for practice in India after FMGE/NExT",
      "Modern infrastructure and clinical exposure from early years",
      "Large Indian student community for support",
    ],
    climate: "Cold winters (-10°C to -20°C) and mild summers (20-25°C). Warm clothing is essential from October to March.",
    faqs: [
      { question: "Is MBBS in Russia valid in India?", answer: "Yes, provided the university is recognized by the NMC and the student clears the FMGE/NExT exam after graduation." },
      { question: "Is NEET mandatory for MBBS in Russia?", answer: "Yes, a valid NEET qualifying score is mandatory for Indian students to get an eligibility certificate." },
      { question: "What is the total cost of MBBS in Russia?", answer: "Total cost including tuition and living expenses ranges between ₹25-35 Lakhs for the full 6-year course." },
    ],
    metaTitle: "MBBS in Russia 2026 - Fees, Eligibility, Top Universities | Medico Overseas",
    metaDescription: "Explore MBBS in Russia with NMC-approved universities, affordable fees, and complete admission guidance. Check eligibility, costs, and application process.",
  },
  {
    slug: "georgia",
    name: "Georgia",
    flagEmoji: "🇬🇪",
    heroImage: "/images/countries/georgia-hero.jpg",
    tagline: "European-standard medical education with easy visa processing",
    overview:
      "Georgia has rapidly become a preferred MBBS destination for Indian students due to its European teaching standards, English-medium curriculum, and simplified visa process. Georgian medical universities follow a curriculum aligned with international standards and are recognized by NMC and WHO.",
    quickFacts: {
      duration: "6 years (including internship)",
      medium: "English",
      intake: "September / October",
      recognition: "WHO, NMC, ECFMG, MCI",
      avgTuitionPerYear: "₹4 - 6 Lakhs",
      avgLivingCostPerYear: "₹2 - 3 Lakhs",
    },
    universities: [
      {
        name: "Tbilisi State Medical University",
        city: "Tbilisi",
        established: 1918,
        ranking: "Top ranked in Georgia",
        recognition: ["NMC", "WHO", "ECFMG"],
      },
      {
        name: "David Tvildiani Medical University",
        city: "Tbilisi",
        established: 1990,
        recognition: ["NMC", "WHO"],
      },
      {
        name: "Georgian National University SEU",
        city: "Tbilisi",
        established: 2004,
        recognition: ["NMC", "WHO"],
      },
    ],
    tuitionFees: [
      { label: "1st Year Tuition", amount: "₹4 - 4.5 Lakhs" },
      { label: "Hostel Fee (per year)", amount: "₹60,000 - 90,000" },
      { label: "One-time Admission Fee", amount: "₹50,000" },
    ],
    livingCosts: [
      { label: "Food", amount: "₹7,000 - 9,000/month" },
      { label: "Local Transport", amount: "₹1,500/month" },
      { label: "Miscellaneous", amount: "₹3,500/month" },
    ],
    eligibility: [
      "Minimum 50% in PCB in 10+2 (45% for reserved categories)",
      "Valid NEET qualifying score",
      "Minimum age of 17 years at the time of admission",
    ],
    admissionProcess: [
      { step: 1, title: "Document Verification", description: "Submit academic records and NEET scorecard for eligibility check." },
      { step: 2, title: "University Selection", description: "Choose from NMC-approved universities in Tbilisi or other cities." },
      { step: 3, title: "Invitation Letter", description: "Receive official admission and invitation letter." },
      { step: 4, title: "Visa Processing", description: "Apply for a Georgian student visa, typically processed within 2-3 weeks." },
      { step: 5, title: "Departure & Enrollment", description: "Travel to Georgia and begin the academic year." },
    ],
    documentsRequired: [
      "10th and 12th mark sheets",
      "NEET admit card and scorecard",
      "Passport (valid for 2+ years)",
      "Passport-size photographs",
      "Birth certificate",
      "Medical fitness certificate",
    ],
    advantages: [
      "European-standard curriculum with modern teaching methods",
      "Simple and fast visa approval process",
      "Safe environment with a growing Indian student community",
      "No entrance exam beyond NEET",
      "Affordable cost of living compared to Western Europe",
    ],
    climate: "Moderate climate with warm summers (25-30°C) and mild winters (0-5°C), generally comfortable year-round.",
    faqs: [
      { question: "Is MBBS in Georgia recognized by NMC?", answer: "Yes, several Georgian medical universities are approved by the National Medical Commission of India." },
      { question: "Do I need to know Georgian language?", answer: "No, the entire MBBS program is taught in English, though basic Georgian is useful for daily life." },
      { question: "What is the total cost of MBBS in Georgia?", answer: "Total cost for the 6-year program including living expenses typically ranges from ₹28-38 Lakhs." },
    ],
    metaTitle: "MBBS in Georgia 2026 - Fees, Eligibility, Top Universities | Medico Overseas",
    metaDescription: "Study MBBS in Georgia at NMC-approved universities with European teaching standards. Get complete details on fees, eligibility, and admission process.",
  },
  {
    slug: "kyrgyzstan",
    name: "Kyrgyzstan",
    flagEmoji: "🇰🇬",
    heroImage: "/images/countries/kyrgyzstan-hero.jpg",
    tagline: "Affordable MBBS with a curriculum designed for Indian students",
    overview:
      "Kyrgyzstan is known for being one of the most budget-friendly MBBS destinations, with universities that have decades of experience teaching Indian medical students. The curriculum is closely aligned with the Indian NEET/NExT pattern, making the transition smoother for Indian graduates.",
    quickFacts: {
      duration: "6 years (including internship)",
      medium: "English",
      intake: "September",
      recognition: "WHO, NMC, ECFMG",
      avgTuitionPerYear: "₹3 - 4.5 Lakhs",
      avgLivingCostPerYear: "₹1.2 - 2 Lakhs",
    },
    universities: [
      {
        name: "Osh State Medical University",
        city: "Osh",
        established: 1939,
        ranking: "Top medical university in Kyrgyzstan",
        recognition: ["NMC", "WHO", "ECFMG"],
      },
      {
        name: "Jalalabad State Medical University",
        city: "Jalalabad",
        established: 1997,
        recognition: ["NMC", "WHO"],
      },
      {
        name: "Kyrgyz State Medical Academy",
        city: "Bishkek",
        established: 1939,
        recognition: ["NMC", "WHO"],
      },
    ],
    tuitionFees: [
      { label: "1st Year Tuition", amount: "₹3 - 3.5 Lakhs" },
      { label: "Hostel Fee (per year)", amount: "₹40,000 - 60,000" },
      { label: "One-time Admission Fee", amount: "₹30,000" },
    ],
    livingCosts: [
      { label: "Food", amount: "₹5,000 - 7,000/month" },
      { label: "Local Transport", amount: "₹1,000/month" },
      { label: "Miscellaneous", amount: "₹2,500/month" },
    ],
    eligibility: [
      "Minimum 50% in PCB in 10+2 (45% for reserved categories)",
      "Valid NEET qualifying score",
      "Minimum age of 17 years at the time of admission",
    ],
    admissionProcess: [
      { step: 1, title: "Document Verification", description: "Submit academic documents and NEET scorecard." },
      { step: 2, title: "University Selection", description: "Choose from Osh, Jalalabad, or Bishkek-based universities." },
      { step: 3, title: "Invitation Letter", description: "Receive the official university invitation letter." },
      { step: 4, title: "Visa Processing", description: "Apply for a Kyrgyz student visa, usually processed quickly." },
      { step: 5, title: "Departure & Enrollment", description: "Travel to Kyrgyzstan and join the academic session." },
    ],
    documentsRequired: [
      "10th and 12th mark sheets",
      "NEET admit card and scorecard",
      "Passport (valid for 2+ years)",
      "Passport-size photographs",
      "Birth certificate",
      "Medical fitness certificate",
    ],
    advantages: [
      "One of the lowest overall costs among MBBS abroad destinations",
      "Large, well-established Indian student community",
      "Curriculum structured to align with FMGE/NExT preparation",
      "No capitation or donation fees",
      "Direct flights and short travel time from India",
    ],
    climate: "Continental climate with cold winters (-5°C to -15°C) and warm summers (25-30°C).",
    faqs: [
      { question: "Is Kyrgyzstan safe for Indian students?", answer: "Yes, Kyrgyzstan has a large, well-settled Indian student community and is considered safe for international students." },
      { question: "Is MBBS in Kyrgyzstan recognized in India?", answer: "Yes, provided the university is NMC-approved and the student clears the FMGE/NExT screening exam." },
      { question: "What is the total MBBS cost in Kyrgyzstan?", answer: "Total cost for the full program is typically the most affordable among popular destinations, around ₹20-28 Lakhs." },
    ],
    metaTitle: "MBBS in Kyrgyzstan 2026 - Fees, Eligibility, Top Universities | Medico Overseas",
    metaDescription: "Affordable MBBS in Kyrgyzstan at NMC-approved universities. Explore fees, eligibility criteria, and step-by-step admission guidance.",
  },
  {
    slug: "uzbekistan",
    name: "Uzbekistan",
    flagEmoji: "🇺🇿",
    heroImage: "/images/countries/uzbekistan-hero.jpg",
    tagline: "Emerging medical education hub with modern facilities",
    overview:
      "Uzbekistan has emerged as a growing destination for MBBS aspirants, offering modern medical infrastructure, English-medium instruction, and a curriculum recognized internationally. Its proximity to India and reasonable costs make it an attractive option for students seeking quality education at accessible fees.",
    quickFacts: {
      duration: "6 years (including internship)",
      medium: "English",
      intake: "September",
      recognition: "WHO, NMC",
      avgTuitionPerYear: "₹3.5 - 5 Lakhs",
      avgLivingCostPerYear: "₹1.5 - 2.2 Lakhs",
    },
    universities: [
      {
        name: "Tashkent Medical Academy",
        city: "Tashkent",
        established: 1919,
        ranking: "Top medical university in Uzbekistan",
        recognition: ["NMC", "WHO"],
      },
      {
        name: "Samarkand State Medical University",
        city: "Samarkand",
        established: 1930,
        recognition: ["NMC", "WHO"],
      },
    ],
    tuitionFees: [
      { label: "1st Year Tuition", amount: "₹3.5 - 4 Lakhs" },
      { label: "Hostel Fee (per year)", amount: "₹45,000 - 70,000" },
      { label: "One-time Admission Fee", amount: "₹35,000" },
    ],
    livingCosts: [
      { label: "Food", amount: "₹6,000/month" },
      { label: "Local Transport", amount: "₹1,200/month" },
      { label: "Miscellaneous", amount: "₹3,000/month" },
    ],
    eligibility: [
      "Minimum 50% in PCB in 10+2 (45% for reserved categories)",
      "Valid NEET qualifying score",
      "Minimum age of 17 years at the time of admission",
    ],
    admissionProcess: [
      { step: 1, title: "Document Verification", description: "Submit academic records and NEET scorecard for eligibility check." },
      { step: 2, title: "University Selection", description: "Choose between Tashkent or Samarkand-based universities." },
      { step: 3, title: "Invitation Letter", description: "Receive the official invitation letter from the university." },
      { step: 4, title: "Visa Processing", description: "Apply for a student visa with required documentation." },
      { step: 5, title: "Departure & Enrollment", description: "Travel to Uzbekistan and complete enrollment formalities." },
    ],
    documentsRequired: [
      "10th and 12th mark sheets",
      "NEET admit card and scorecard",
      "Passport (valid for 2+ years)",
      "Passport-size photographs",
      "Birth certificate",
      "Medical fitness certificate",
    ],
    advantages: [
      "Modern campuses with updated medical equipment",
      "Growing recognition among Indian MBBS aspirants",
      "Reasonable tuition with no hidden donation costs",
      "Short flight duration from major Indian cities",
      "Increasing Indian student presence and support networks",
    ],
    climate: "Continental climate with hot summers (30-35°C) and cold winters (-5°C to 5°C).",
    faqs: [
      { question: "Is MBBS in Uzbekistan good for Indian students?", answer: "Yes, Uzbekistan offers NMC-approved universities with modern infrastructure and increasingly popular among Indian students." },
      { question: "Is the medium of instruction English?", answer: "Yes, MBBS programs for international students are taught entirely in English." },
      { question: "What is the total cost of MBBS in Uzbekistan?", answer: "Total cost for the 6-year program including living expenses is approximately ₹25-32 Lakhs." },
    ],
    metaTitle: "MBBS in Uzbekistan 2026 - Fees, Eligibility, Top Universities | Medico Overseas",
    metaDescription: "Pursue MBBS in Uzbekistan at NMC-approved universities with modern facilities. View fees, eligibility, and admission process details.",
  },
  {
    slug: "armenia",
    name: "Armenia",
    flagEmoji: "🇦🇲",
    heroImage: "/images/countries/armenia-hero.jpg",
    tagline: "Quality medical education with a curriculum aligned to global standards",
    overview:
      "Armenia is home to some of the oldest and most reputed medical universities in the region, offering globally aligned curricula with strong clinical training. With a peaceful environment and growing Indian student base, Armenia is a solid choice for aspiring doctors.",
    quickFacts: {
      duration: "6 years (including internship)",
      medium: "English",
      intake: "September",
      recognition: "WHO, NMC, ECFMG",
      avgTuitionPerYear: "₹4 - 5.5 Lakhs",
      avgLivingCostPerYear: "₹1.8 - 2.5 Lakhs",
    },
    universities: [
      {
        name: "Yerevan State Medical University",
        city: "Yerevan",
        established: 1922,
        ranking: "Top ranked in Armenia",
        recognition: ["NMC", "WHO", "ECFMG"],
      },
      {
        name: "Armenian Medical Institute",
        city: "Yerevan",
        established: 1990,
        recognition: ["NMC", "WHO"],
      },
    ],
    tuitionFees: [
      { label: "1st Year Tuition", amount: "₹4 - 4.5 Lakhs" },
      { label: "Hostel Fee (per year)", amount: "₹55,000 - 80,000" },
      { label: "One-time Admission Fee", amount: "₹45,000" },
    ],
    livingCosts: [
      { label: "Food", amount: "₹6,500 - 8,000/month" },
      { label: "Local Transport", amount: "₹1,500/month" },
      { label: "Miscellaneous", amount: "₹3,000/month" },
    ],
    eligibility: [
      "Minimum 50% in PCB in 10+2 (45% for reserved categories)",
      "Valid NEET qualifying score",
      "Minimum age of 17 years at the time of admission",
    ],
    admissionProcess: [
      { step: 1, title: "Document Verification", description: "Submit academic records and NEET scorecard for eligibility check." },
      { step: 2, title: "University Selection", description: "Choose from Yerevan-based medical universities." },
      { step: 3, title: "Invitation Letter", description: "Receive official invitation letter from the university." },
      { step: 4, title: "Visa Processing", description: "Apply for an Armenian student visa." },
      { step: 5, title: "Departure & Enrollment", description: "Travel to Armenia and begin the academic year." },
    ],
    documentsRequired: [
      "10th and 12th mark sheets",
      "NEET admit card and scorecard",
      "Passport (valid for 2+ years)",
      "Passport-size photographs",
      "Birth certificate",
      "Medical fitness certificate",
    ],
    advantages: [
      "Century-old medical universities with strong academic legacy",
      "Globally aligned curriculum with early clinical exposure",
      "Peaceful and safe environment for international students",
      "No entrance exam beyond NEET",
      "Recognized by major global medical bodies",
    ],
    climate: "Continental climate with hot dry summers (30°C+) and cold winters (-5°C to -10°C).",
    faqs: [
      { question: "Is MBBS in Armenia recognized by NMC?", answer: "Yes, leading Armenian medical universities are approved by the National Medical Commission." },
      { question: "How old are Armenian medical universities?", answer: "Some, like Yerevan State Medical University, have been operating for over 100 years with strong academic reputations." },
      { question: "What is the total cost of MBBS in Armenia?", answer: "Total cost for the full 6-year program including living expenses ranges from ₹30-40 Lakhs." },
    ],
    metaTitle: "MBBS in Armenia 2026 - Fees, Eligibility, Top Universities | Medico Overseas",
    metaDescription: "Study MBBS in Armenia at century-old, NMC-approved medical universities. Explore fees, eligibility, and complete admission guidance.",
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    flagEmoji: "🇻🇳",
    heroImage: "/images/countries/vietnam-hero.jpg",
    tagline: "A rising destination combining quality education and rich culture",
    overview:
      "Vietnam is an emerging MBBS destination offering a blend of quality medical education, modern hospitals for clinical training, and a relatively low cost of living. While a newer option for Indian students, its universities are gaining recognition for infrastructure and teaching standards.",
    quickFacts: {
      duration: "6 years (including internship)",
      medium: "English",
      intake: "September",
      recognition: "WHO, NMC",
      avgTuitionPerYear: "₹4.5 - 6 Lakhs",
      avgLivingCostPerYear: "₹1.8 - 2.5 Lakhs",
    },
    universities: [
      {
        name: "Hanoi Medical University",
        city: "Hanoi",
        established: 1902,
        ranking: "Top medical university in Vietnam",
        recognition: ["NMC", "WHO"],
      },
      {
        name: "Vietnam Military Medical University",
        city: "Hanoi",
        established: 1949,
        recognition: ["NMC", "WHO"],
      },
    ],
    tuitionFees: [
      { label: "1st Year Tuition", amount: "₹4.5 - 5 Lakhs" },
      { label: "Hostel Fee (per year)", amount: "₹60,000 - 85,000" },
      { label: "One-time Admission Fee", amount: "₹50,000" },
    ],
    livingCosts: [
      { label: "Food", amount: "₹7,000/month" },
      { label: "Local Transport", amount: "₹1,500/month" },
      { label: "Miscellaneous", amount: "₹3,000/month" },
    ],
    eligibility: [
      "Minimum 50% in PCB in 10+2 (45% for reserved categories)",
      "Valid NEET qualifying score",
      "Minimum age of 17 years at the time of admission",
    ],
    admissionProcess: [
      { step: 1, title: "Document Verification", description: "Submit academic records and NEET scorecard for eligibility check." },
      { step: 2, title: "University Selection", description: "Choose from Hanoi-based medical universities." },
      { step: 3, title: "Invitation Letter", description: "Receive official invitation letter from the university." },
      { step: 4, title: "Visa Processing", description: "Apply for a Vietnamese student visa." },
      { step: 5, title: "Departure & Enrollment", description: "Travel to Vietnam and begin the academic session." },
    ],
    documentsRequired: [
      "10th and 12th mark sheets",
      "NEET admit card and scorecard",
      "Passport (valid for 2+ years)",
      "Passport-size photographs",
      "Birth certificate",
      "Medical fitness certificate",
    ],
    advantages: [
      "Modern hospitals providing strong clinical exposure",
      "Rich culture and welcoming environment for international students",
      "Growing recognition of Vietnamese medical degrees",
      "Reasonable cost of living compared to Western countries",
      "Safe and stable environment for studies",
    ],
    climate: "Tropical climate with hot, humid summers (30-35°C) and mild winters (15-20°C).",
    faqs: [
      { question: "Is MBBS in Vietnam recognized in India?", answer: "Recognition depends on the specific university; students should verify NMC approval before applying." },
      { question: "Is Vietnam a good option for MBBS abroad?", answer: "It's a newer but growing option with modern hospitals and reasonable costs, suited for students open to an emerging destination." },
      { question: "What is the total cost of MBBS in Vietnam?", answer: "Total cost for the full 6-year program including living expenses ranges from ₹32-42 Lakhs." },
    ],
    metaTitle: "MBBS in Vietnam 2026 - Fees, Eligibility, Top Universities | Medico Overseas",
    metaDescription: "Explore MBBS in Vietnam with modern hospitals and quality medical education. Check fees, eligibility, and admission process details.",
  },
];

export function getCountryBySlug(slug: string): Country | undefined {
  return countries.find((c) => c.slug === slug);
}

export function getAllCountrySlugs(): string[] {
  return countries.map((c) => c.slug);
}